version: '3.0'

services:
  clash:
    image: alanwoods/clash
    container_name: clash
    ports:
      - "7890:7890"
      - "7892:7892"
    privileged: true
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/clash:/app/config
