version: '3.0'

services:
  clash:
    image: alanwoods/clash
    container_name: clash
    network_mode: host
    privileged: true
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/clash:/app/config