version: '3.0'

services:
  clash:
    image: alanwoods/clash:arm64
    container_name: clash
    network_mode: host
    privileged: true
    restart: always
    environment:
      TZ: Asia/Shanghai
      SUBNET: 192.168.51.0/24
    volumes:
      - /data/clash:/app/config
