version: '3.0'

services:
  clash:
    image: alanwoods/clash
    container_name: clash
    # crate macnet first
    # ip link set eth0 promisc on
    # docker network create -d macvlan --subnet=192.168.31.0/24 --gateway=192.168.31.1 -o parent=eth0 macnet
    network_mode: macnet
    privileged: true
    restart: always
    environment:
      SUBNET: 192.168.1.0/24
      TZ: Asia/Shanghai
    volumes:
      - /data/clash:/app/config
